# Generated by Django 4.2.23 on 2025-08-12 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid_utils.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("year", models.SmallIntegerField(verbose_name="year")),
            ],
            options={
                "verbose_name": "album",
                "verbose_name_plural": "albums",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
            ],
            options={
                "verbose_name": "artist",
                "verbose_name_plural": "artists",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="title")),
            ],
            options={
                "verbose_name": "track",
                "verbose_name_plural": "tracks",
            },
        ),
        migrations.CreateModel(
            name="AlbumTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(verbose_name="#")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="albums.album"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="albums.track"
                    ),
                ),
            ],
            options={
                "verbose_name": "tracks for album",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="albums.artist",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(
                through="albums.AlbumTrack", to="albums.track"
            ),
        ),
        migrations.AddConstraint(
            model_name="albumtrack",
            constraint=models.UniqueConstraint(
                fields=("album", "position"),
                name="unique_track_position",
                violation_error_message="Each track in an album shall have its own unique position",
            ),
        ),
    ]
